### ISSUE TITLE
相对于dingdang，有什么优缺点么

### ISSUE THREAD

**Issue by dream10201** [jjwang/laibot#3]

**Comment by jjwang** [comment]
laibot和其他Jasper派生出的项目，最大的区别就是：
- laibot特别关注语音识别的性能表现，追求在免费服务下的最好性能表现。

从现在laibot的迭代历史可以看出：
- v0.1：版本初步可用。
- v0.2：转移到python3，以解决中文字符转码问题。
- v0.3：当前版本，大改动有：1、引入webrtcvad来做语音活动检测，较Jasper原有版本改善很大；2、将基于PocketSphinx的离线式的语音唤醒改成在线流式的了，延迟也有很大改进。还在优化中，v0.3尚未定版。

laibot的硬件选型也是有特色的，TJBot是一个完善的平台，拥有3D打印专业的外壳，还有电机驱动的臂、摄像头、指示状态的RGB灯等，可以认为是一个较完美的机器人平台。TJBot的3D打印外壳淘宝也可以购买到，搜索TJBot即可以看到。

后续laibot还会有一个音箱形态的展示，目前外壳已选择好，敬请期待。

**Comment by dream10201** [comment]
玩过叮当，唤醒率和误唤醒率问题太大，所以没深入了，希望laibot在这两个点能有所改善

**Comment by jjwang** [comment]
唤醒率和误唤醒率latbot后续版本会有相当大的改善，请放心。

另外，语音会话时，联网识别合成也延迟较大，不知道你关注过没？

**Comment by dream10201** [comment]
如果用于对话，延迟确实会有影响
